spring.application.name=jdbc
# spring.datasource.url, 이게 없으면 스프링 부트는 내장 데이터 베이스(메모리DB)를 생성하려고 한다
spring.datasource.url=jdbc:h2:tcp://localhost/~/test
spring.datasource.username=sa
spring.datasource.password=